apiVersion: v1
kind: Pod
metadata:
  name: kuard
  labels:
    name: kuard
spec:
  volumes:
    - name: "kuard-data"
      nfs:
        path: my.nfs.server.local
        server: "/exports"
  containers:
  - name: kuard
    image: gcr.io/kuar-demo/kuard-amd64:blue
    livenessProbe:
      httpGet:
        path: /healthy
        port: 8080
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      initialDelaySeconds: 30
      timeoutSeconds: 1
    resources:
      requests:
        cpu: "500m"
        memory: "128Mi"
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - mountPath: "/data"
        name: "kuard-data"
    ports:
      - containerPort: 8080
        name: http
        protocol: TCP

