apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: pods-and-services
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: Thiago
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: mydevs
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: pod-and-services