apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: alpaca-test
  labels:
    enviroment: "test"
    app: alpaca
    ver: "1"
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:    
      containers:
      - name: alpaca-test
        image: "gcr.io/kuar-demo/kuard-amd64:green"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 8080